### ISSUE TITLE
Support for gifs and JPEG

### ISSUE THREAD

**Issue by aberba** [georgy7/dlib-webp#1]
Does it fit in this project to add support for converting gif and jpeg in addition to png?

More over, mp4, * to webm (video).

**Comment by georgy7** [comment]
Hi!
I think, it's better to create separate project or projects.
This library has the very specific goal - make WebP support for dlib's SuperImage class.
Even this goal, although it has been reached, requires inspection and additional unit tests. There is still a lot of work to do.
If you want to create the library with many additional formats for dlib, you could use my code as dependency or fork or assimilate it.

**Comment by georgy7** [comment]
Also, you already have the ability to read from JPEG.
https://github.com/gecko0307/dlib/wiki/dlib.image
