### ISSUE TITLE
saveWEBP

### ISSUE THREAD

**Issue by trikko** [georgy7/dlib-webp#5]
I think something like this could fit better.

```d
enum WEBPQuality : int
{
   LOSSLESS = -1,
   LOW = 0,
   ...
   HIGH = 100
}

void saveWEBP(string filename, int quality = WEBPQuality.LOSSLESS)
{
	...
}
```

So you can use like this:

```d
img.saveWEBP("lossless.webp");
img.saveWEBP("high.webp", WEBPQuality.HIGH);
img.saveWEBP("high.webp", 60);
```

**Comment by georgy7** [comment]
This makes sense.

I would use the quality gradation based on that source:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization#how-does-webp-perform

LOWEST - 0
LOW - 50
MEDIUM - 75
HIGH - 80
HIGHEST - 100

Something like this.
I could not find anything better than this.

**Comment by georgy7** [comment]
The default quality is 75 in cwebp.

https://developers.google.com/speed/webp/docs/cwebp#options

**Comment by trikko** [comment]
So maybe it should be:
```d
void saveWEBP(string filename, int quality = WEBPQuality.DEFAULT)
{
	...
}
```

Another suggestion. Why not:

```d
import std.typecons : Flag, Yes, No;

void saveWEBP(Flag!"alpha" alpha = Yes.alpha)(string filename, int quality = WEBPQuality.LOSSLESS)
{
   
}

void main()
{
    saveWEBP("hello.webp", 50);
    saveWEBP("hello.webp", WEBPQuality.LOSSLESS);
    saveWEBP!(No.alpha)("hello.webp", 10);
   saveWEBP!(Yes.alpha)("bla.webp", 10);
}
```

**Comment by georgy7** [comment]
SuperImage already has pixelFormat.

It's just:

```
auto withoutAlpha = convert!(Image!(PixelFormat.RGB8))(img);
withoutAlpha.saveWEBP("hello.webp");
```

Webp has other interesting features like "alpha quality", etc. Although, I don't have time to add these features right now anyway.

Thanks for your contribution.

**Comment by georgy7** [comment]
Also, I found out that libwebp 0.6.1 with that library produces broken lossless files in 5-10% cases. Libwebp ABI changed many times. All Linux distibutions has different versions. And I don't know, what to do with that.
